#include "../globals.h"
#include "io.h"

void Read_Parameter_File(char *filename)
{
	char buf[CHARBUFSIZE], buf1[CHARBUFSIZE],buf2[CHARBUFSIZE],
		 buf3[CHARBUFSIZE];
	bool tagDone[NTags];
	int i, j;
	
	if (!Task.Rank) {

		FILE *fd = fopen(filename, "r");

		Assert(fd != NULL, "Parameter file not found %s \n", filename);
			
		printf("\nReading Parameter file: %s \n", filename);
			
		while (fgets(buf, CHARBUFSIZE, fd)) {

			if (sscanf(buf, "%s%s%s", buf1, buf2,buf3) < 2)
				continue;

			if (buf1[0] == '%') // commented out
				continue;

			for (i = 0, j = -1; i < NTags; i++) {
				
				int tagNotFound = strcmp(buf1, ParDef[i].tag);
				
				if (!tagNotFound && !tagDone[i]) {

					j = i;

					tagDone[i] = true;
					
					break;
				}
			}

			if (j<0) // don't know this one
				continue;
				
			printf(" %20s     %s\n", buf1, buf2);

			switch (ParDef[j].type) {
			case FLOAT:
				
				*((double *)ParDef[j].addr) = atof(buf2);
				
				break;
			case STRING:
			
				strncpy((char *)ParDef[j].addr, buf2, CHARBUFSIZE);
				
				break;
			case INT:
				
				*((int *)ParDef[j].addr) = atoi(buf2);
				
				break;
			}
		}
		
		fclose(fd);
		
		printf("\n");

		for (i = 0; i < NTags; i++) // are we missing one ?
            Assert(tagDone[i],"Value for tag '%s' missing in parameter"
					" file '%s'.\n",ParDef[i].tag, filename );
	}

	/* routine checks */
	Assert(Param.No_Output_Files <= Task.NTask, 
			"NTask (%d) can't be smaller than No_IOTasks (%d)", 
			Task.NTask,  Param.No_Output_Files);
	Assert(Param.Boxsize > 0, "Boxsize (%d) has to be > 0", Param.Boxsize);


	MPI_Bcast(&Param, sizeof(Param), MPI_BYTE, 0, MPI_COMM_WORLD);

	return ;
}

void Write_Parameter_File(char *filename)
{
	if (!Task.Rank) {
		printf("\nWriting Parameter file: %s \n", filename);

		FILE *fd = fopen(filename, "w");

		Assert(fd != NULL, "Can't open file %s for writing \n", filename);

		fprintf(fd, "%% Widget, autogenerated parameter file %% \n\n");
		
		for (int i = 0; i < NTags; i++)
			fprintf(fd, "%s		%s \n", ParDef[i].tag, ParDef[i].val);

		fclose(fd);

		printf("\ndone, Good Bye.\n\n");
	}

	MPI_Barrier(MPI_COMM_WORLD);

	exit(EXIT_SUCCESS);

	return ;
}
