/* Autogenerated File  */
#include "globals.h"
#include "proto.h"
void Print_compile_time_settings(){
	rprintf("Compiled with : \n"
"      GRAVITY				// gravitational interaction \n"
"      UNITS_GADGET_STD 	// kpc, 10^10 Msol, km/s \n"
); return ;}
